# Generated by Django 2.0.2 on 2022-12-13 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='aLirePlusTard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BX_Book_Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Rating', models.IntegerField()),
                ('ISBN', models.CharField(max_length=200, null=True)),
                ('User_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BX_Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BX_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenue', models.CharField(max_length=5000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('note', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('nom', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='livre_image')),
                ('image_livre', models.CharField(blank=True, max_length=1000, null=True)),
                ('editeur', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_pages', models.IntegerField(blank=True, null=True)),
                ('date_parution', models.DateField(blank=True, null=True)),
                ('anee_parution', models.IntegerField(null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, null=True)),
                ('limite_age', models.IntegerField(blank=True, max_length=200, null=True)),
                ('desctiption', models.CharField(max_length=2000, null=True)),
                ('langue', models.CharField(blank=True, max_length=200, null=True)),
                ('public_cible', models.CharField(blank=True, max_length=200, null=True)),
                ('auteurs', models.ManyToManyField(blank=True, related_name='livres', to='Livres.Auteur')),
                ('genres', models.ManyToManyField(related_name='livres', to='Livres.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livres.Livre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('pays', models.CharField(max_length=50)),
                ('specialite', models.CharField(max_length=100, null=True)),
                ('genre', models.ManyToManyField(null=True, related_name='profils', to='Livres.Genre')),
                ('langues', models.ManyToManyField(related_name='profils', to='Livres.Langue')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='favoris',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livres.Livre'),
        ),
        migrations.AddField(
            model_name='favoris',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livres.Livre'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alireplustard',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livres.Livre'),
        ),
        migrations.AddField(
            model_name='alireplustard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
